- platform: xiaomi_miio_airconditioningcompanion
  name: Aqara Air Conditioning Companion
  host: 192.168.11.137
  token: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  target_sensor: sensor.t2_cloud_m0ek00_temperature
  scan_interval: 60